-- Initial SIEM schema: the sources that produce logs, the events they produce, the rules
-- evaluated against those events, and the alerts that result.
--
-- Flyway owns this file's output outright. Hibernate runs with
-- quarkus.hibernate-orm.schema-management.strategy=validate and never emits DDL, so every
-- later change to an entity has to arrive as a new V<n>__*.sql migration. Once this file has
-- been applied anywhere it is immutable — Flyway checksums it.
--
-- Enumerated columns are TEXT with a CHECK constraint rather than native PostgreSQL enum
-- types: adding a value here is a constraint swap local to one table, while altering an enum
-- type reaches every object that depends on it.

CREATE TABLE log_source (
    id         BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       TEXT        NOT NULL,
    type       TEXT        NOT NULL,
    hostname   TEXT,
    enabled    BOOLEAN     NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),

    CONSTRAINT uq_log_source_name UNIQUE (name),
    CONSTRAINT ck_log_source_type CHECK (
        type IN ('SYSLOG', 'FIREWALL', 'CLOUD_TRAIL', 'APPLICATION', 'ENDPOINT')
    )
);

-- Append-only. Nothing updates a row here; corrections belong in derived tables. A row read
-- today has to be byte-identical to the same row read in three months, otherwise a training
-- dataset built from this table is not reproducible.
CREATE TABLE log_event (
    id          BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_id   BIGINT      NOT NULL,
    -- Identifier carried by the upstream record, used to discard replays. Nullable, because
    -- not every source provides one.
    external_id TEXT,
    -- When the event happened, as reported by the source.
    occurred_at TIMESTAMPTZ NOT NULL,
    -- When we stored it. Kept apart from occurred_at because the gap between the two is
    -- ingestion lag, and it cannot be reconstructed after the fact from a single column.
    ingested_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    severity    TEXT        NOT NULL,
    -- Parsed, human-readable summary.
    message     TEXT        NOT NULL,
    -- The original line exactly as received. The one column in this schema that cannot be
    -- backfilled: model training runs against the raw log, not against parsed fields, so an
    -- event ingested without it is permanently unusable for that purpose.
    raw         TEXT        NOT NULL,
    -- Parsed structured fields, when the source has any.
    payload     JSONB,

    CONSTRAINT fk_log_event_source FOREIGN KEY (source_id) REFERENCES log_source (id),
    CONSTRAINT ck_log_event_severity CHECK (
        severity IN ('DEBUG', 'INFO', 'WARNING', 'ERROR', 'CRITICAL')
    )
);

-- PostgreSQL treats NULLs as distinct in a unique index, so sources without an external id
-- are left unconstrained and only genuine duplicates are rejected.
CREATE UNIQUE INDEX uq_log_event_external_id ON log_event (external_id);

-- Time-range scans are the dominant read pattern, per source and across all of them.
CREATE INDEX ix_log_event_occurred_at ON log_event (occurred_at DESC);
CREATE INDEX ix_log_event_source_occurred_at ON log_event (source_id, occurred_at DESC);

-- Structured field search over the parsed payload.
CREATE INDEX ix_log_event_payload ON log_event USING GIN (payload);

CREATE TABLE alert_rule (
    id          BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        TEXT        NOT NULL,
    description TEXT,
    severity    TEXT        NOT NULL,
    -- The rule body. Opaque to the persistence layer; whatever evaluates rules owns its
    -- syntax.
    expression  TEXT        NOT NULL,
    enabled     BOOLEAN     NOT NULL DEFAULT TRUE,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT now(),

    CONSTRAINT uq_alert_rule_name UNIQUE (name),
    CONSTRAINT ck_alert_rule_severity CHECK (
        severity IN ('DEBUG', 'INFO', 'WARNING', 'ERROR', 'CRITICAL')
    )
);

CREATE TABLE alert (
    id           BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- Nullable: an alert raised by a model has no rule behind it. Nullable from the start
    -- costs nothing, whereas dropping a NOT NULL on a populated alerts table later does not.
    rule_id      BIGINT,
    log_event_id BIGINT      NOT NULL,
    title        TEXT        NOT NULL,
    detail       TEXT,
    severity     TEXT        NOT NULL,
    status       TEXT        NOT NULL DEFAULT 'OPEN',
    raised_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    resolved_at  TIMESTAMPTZ,

    CONSTRAINT fk_alert_rule FOREIGN KEY (rule_id) REFERENCES alert_rule (id),
    CONSTRAINT fk_alert_log_event FOREIGN KEY (log_event_id) REFERENCES log_event (id),
    CONSTRAINT ck_alert_severity CHECK (
        severity IN ('DEBUG', 'INFO', 'WARNING', 'ERROR', 'CRITICAL')
    ),
    CONSTRAINT ck_alert_status CHECK (
        status IN ('OPEN', 'ACKNOWLEDGED', 'RESOLVED', 'FALSE_POSITIVE')
    )
);

-- The triage queue: open alerts, newest first.
CREATE INDEX ix_alert_status_raised_at ON alert (status, raised_at DESC);
CREATE INDEX ix_alert_rule ON alert (rule_id);
CREATE INDEX ix_alert_log_event ON alert (log_event_id);
