-- Application accounts and their roles.
--
-- Same contract as V1: Flyway owns this DDL outright, Hibernate only validates against it,
-- and this file is immutable once applied anywhere. Any later change arrives as V3.

-- Named app_user rather than "user": user is a reserved word in PostgreSQL, so every
-- unquoted reference to it would resolve to the current_user function instead of the table,
-- and quoting it everywhere is a permanent tax on the rest of the schema.
CREATE TABLE app_user (
    id            BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- Login identifier. Case is stored as entered; uniqueness is on the exact string.
    username      TEXT        NOT NULL,
    -- Nullable: an account created for a service or a shared console has no mailbox.
    email         TEXT,
    -- Argon2id encoded hash, salt and parameters included, as produced by password4j:
    -- $argon2id$v=19$m=...,t=...,p=...$<salt>$<hash>. The plaintext is never stored and the
    -- verification parameters are read back from this string, so raising the cost settings
    -- later leaves existing rows verifiable.
    password_hash TEXT        NOT NULL,
    enabled       BOOLEAN     NOT NULL DEFAULT TRUE,
    created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at    TIMESTAMPTZ NOT NULL DEFAULT now(),

    CONSTRAINT uq_app_user_username UNIQUE (username),
    CONSTRAINT uq_app_user_email UNIQUE (email),
    -- A hash is either a full Argon2 encoding or the locked marker below; nothing else is a
    -- value this application ever writes, and a row holding something else would silently
    -- fail every login instead of being rejected at write time.
    CONSTRAINT ck_app_user_password_hash CHECK (
        password_hash = '!' OR password_hash LIKE '$argon2%'
    )
);

-- Roles as rows rather than as a column on app_user: an account can hold several at once,
-- and the set is read on every authorisation decision, so it stays a plain join instead of a
-- parsed string.
CREATE TABLE user_role (
    user_id BIGINT NOT NULL,
    role    TEXT   NOT NULL,

    PRIMARY KEY (user_id, role),
    CONSTRAINT fk_user_role_user FOREIGN KEY (user_id) REFERENCES app_user (id) ON DELETE CASCADE,
    CONSTRAINT ck_user_role CHECK (role IN ('ADMIN', 'ANALYST', 'VIEWER'))
);

-- Bootstrap administrator.
--
-- The hash is the locked marker '!', not a real password: it is not valid Argon2, so
-- verification rejects it for every input and the account cannot be logged into as shipped.
-- A seeded credential would otherwise be identical on every deployment that runs this
-- migration, including production, which is the one thing a security product must not ship.
-- The row still does the work a seed is for -- it reserves the username and guarantees at
-- least one ADMIN exists -- and the password is set once, per environment:
--
--   PUT /api/users/1/password  {"password": "<chosen>"}
INSERT INTO app_user (username, email, password_hash, enabled)
VALUES ('admin', NULL, '!', TRUE);

INSERT INTO user_role (user_id, role)
SELECT id, 'ADMIN' FROM app_user WHERE username = 'admin';
