-- Authentication events, for investigation after the fact.
--
-- Same contract as V1 and V2: Flyway owns this DDL, Hibernate only validates against it, and
-- this file is immutable once applied anywhere.
CREATE TABLE auth_event (
    id          BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    occurred_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    type        TEXT        NOT NULL,
    -- The identifier as submitted, kept even when no account carries it: a failed sign-in
    -- against a username that does not exist is exactly the event an investigation needs, and
    -- it has no row in app_user to point at.
    username    TEXT,
    -- Nullable and ON DELETE SET NULL: the history of an account outlives the account. A
    -- deleted user must not take the record of its own sign-ins with it.
    user_id     BIGINT,
    client_ip   TEXT,
    -- Free-text context for the type: which family a reuse was detected in, why a sign-in was
    -- refused. Not a structured column, because nothing queries inside it.
    detail      TEXT,

    CONSTRAINT fk_auth_event_user FOREIGN KEY (user_id) REFERENCES app_user (id) ON DELETE SET NULL,
    CONSTRAINT ck_auth_event_type CHECK (type IN (
        'LOGIN_SUCCESS', 'LOGIN_FAILURE', 'REFRESH', 'REFRESH_REUSE', 'LOGOUT', 'RATE_LIMITED'
    ))
);

-- The two questions this table is read with: what happened recently, and what happened to this
-- username.
CREATE INDEX ix_auth_event_occurred_at ON auth_event (occurred_at DESC);
CREATE INDEX ix_auth_event_username ON auth_event (username, occurred_at DESC);
