-- Uploaded log files and their metadata, awaiting or undergoing ingestion.
--
-- Same contract as V1-V3: Flyway owns this DDL, Hibernate validates against it.
CREATE TABLE log_upload (
    id              BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_id       BIGINT,
    file_name       TEXT        NOT NULL,
    content_type    TEXT,
    file_size       BIGINT      NOT NULL,
    checksum_sha256 TEXT        NOT NULL,
    storage_path    TEXT,
    status          TEXT        NOT NULL DEFAULT 'PENDING',
    uploaded_by     TEXT,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),

    CONSTRAINT fk_log_upload_source FOREIGN KEY (source_id) REFERENCES log_source (id) ON DELETE SET NULL,
    CONSTRAINT ck_log_upload_status CHECK (status IN ('PENDING', 'PROCESSING', 'INGESTED', 'FAILED'))
);

CREATE INDEX ix_log_upload_created_at ON log_upload (created_at DESC);
CREATE INDEX ix_log_upload_source ON log_upload (source_id);
CREATE INDEX ix_log_upload_checksum ON log_upload (checksum_sha256);
